### ISSUE TITLE
host linki

### ISSUE THREAD

**Issue by fahricigdem** [hkn96/NEUMORPHISM-CALCULATOR-DESIGN#1]
Hakan abi bu yaptigin calisma icin github'i host olarak kullanabilirsin. Sonra senin icin bir link uretiliyor. Bu linki kullanarak her daim farkli farkli cihazlardan canli olarak yaptigin calismayi gorebilir/gösterebilirsin. Örnek: https://2-gruppe.github.io/Webseite-2.Gruppe/

**Comment by hkn96** [comment]
Danke 👍👍👍
________________________________
